### PR TITLE
fix: removed url from the WAI sub value, just thumbprint

### LINKED ISSUE #52: Iss in the Wallet Instance Attestation Request should be the same as sub in Response
**iss** in the Wallet Instance Attestation Request payload is defined as:
`The thumbprint of the JWK of the Wallet Instance or which the attestation is  being requested.`

In the payload of the Wallet Instance Attestation **sub** is defined as:
`The public url of the issuer concatenated with the thumbprint of the JWK of the Wallet Instance for which the attestation is being issued.`

Shouldn't they be the same ?

### PR DESCRIPTION
**Pull request by peppelinux**
Roland Hedberg rev

- typo fixed on WAI sub value

### CODE REVIEW

**Comment by balanza** [comment]
What was the typo? Sorry, it's difficult to spot it as the whole file appears as changed.

**Comment by balanza** [comment]
> What was the typo? Sorry, it's difficult to spot it as the whole file appears as changed.

Ok I got it.

|new|old|
|-|-|
|Thumbprint value of the JWK of the Wallet Instance for which the attestation is being issued.|The public url of the issuer concatenated with the thumbprint of the JWK of the Wallet Instance for which the attestation is being issued.|

It's more a different specification than a typo, isn't it?

**Comment by peppelinux** [comment]
> What was the typo? Sorry, it's difficult to spot it as the whole file appears as changed.

yes, I just ficed the commit since those "automatic" tables are something messy when something changes within them. Now the PR is more readable, thank you for having pointed this out

**Comment by peppelinux** [comment]
> > What was the typo? Sorry, it's difficult to spot it as the whole file appears as changed.
> 
> Ok I got it.
> new 	old
> Thumbprint value of the JWK of the Wallet Instance for which the attestation is being issued. 	The public url of the issuer concatenated with the thumbprint of the JWK of the Wallet Instance for which the attestation is being issued.
> 
> It's more a different specification than a typo, isn't it?

I'd say that's typo due to a regression happened when we have decided to drop the URL from the sub and use just the thumbprint, but feel free to change the title of this PR

**Review by grausof — APPROVED** [review]

**Pull request merged**
